version: '3'
services:
    odoo:
        container_name: odoo
        image: odoo:${ODOO_VERSION}
        depends_on:
            - db
        volumes:
            - ./addons-extra:/mnt/extra-addons
            - ./config/odoo:/etc/odoo
            - odoo-web-data:/var/lib/odoo
        ports:
            - "8069:8069"
    db:
        container_name: postgres
        image: postgres:${DB_VERSION}
        env_file:
            - .env
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_USER=${DB_NAME}
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            - odoo-db-data:/var/lib/postgresql/data/pgdata
    nginx:
        container_name: nginx
        image: nginx:latest
        env_file:
            - .env
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./config/nginx:/etc/nginx/conf.d
volumes:
    odoo-web-data:
    odoo-db-data:
